### ISSUE TITLE
Release 0.2.0 Overview

### ISSUE THREAD

**Issue by joshbruce** [8fold/html5-generator-php#26]
Definition of done: Element complies with the other hight priority items in this milestone.

- [x] global attributes W3C example tests
  - [x] accesskey
  - [x] class
  - [x] content editable
  - [x] dir
  - [x] hidden
  - [x] id
  - [x] lang
  - [x] spellcheck
  - [x] style
  - [x] tabindex
  - [x] title
  - [x] translate
- [x] html
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] head
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] title
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] base
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] link
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] meta
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] style
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] body
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] article
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
  - [x] tests for W3C examples #3 
- [x] section
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- [x] nav
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- [x] aside
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- header
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- footer
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- address
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- h1, h2, h3, h4, h5, h6
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- p
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- hr
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- pre
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- block quote
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- ol
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- ul
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- li
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- dl
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- dt
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- dd
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- figure
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- figcaption
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- div
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- main
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- a
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- em
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- strong
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- small
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- s
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- q
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- dfn
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- abbr
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- data
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- time
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- code
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- variable
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- samp
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- kdb
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- cite
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- sup
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- sub
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
-  i
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- b
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- u
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- mark
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- ruby
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- rb
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- rt
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- rtc
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- rp
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- bid
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- bdo
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- span
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- br
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- wbr
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- ins
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- del
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- img
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- iframe
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- embed
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- object
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- param
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- video
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- source
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- track
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- audio
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- map
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- area
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- table
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- caption
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- colgroup
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- col
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- thead
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- tbody
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- tfoot
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- tcell
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- tr
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- form
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- label
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- input
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- select
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- option
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- optgroup
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- datalist
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- textarea
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- output
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- progress
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- meter
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- fieldset
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- legend
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] allow setting valid types #9 
  - [x] space-separated attributes accept arrays #8 
- script
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- noscript
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- template
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8 
- canvas
  - [x] confirm optional attributes are in OPTIONAL_KEYS #24 
  - [x] space-separated attributes accept arrays #8

**Comment by joshbruce** [comment]
Ran into a naming collision with `title`. The `head` element has a `title` key to generate a descendent. The GLOBALS have a `title` attribute.

Renaming `title` attribute to `titleAttribute` to see if it resolves the issues.

**Comment by joshbruce** [comment]
After writing `testArticle2` - I believe the current solution is demonstrating itself well. The increased complexity of the examples is stress-testing the Generator pretty well; however, I believe we are starting to slide into territory the Generator was not meant to necessarily go - as an extendable library...namely a template engine in its own right.

Instead of writing unit tests for each one of the element, I think the Generator would be better served if we examine the examples for things that have not yet been accounted for - micro data, for example.

**Comment by joshbruce** [comment]
The following combination is happening often:

```
  const OPTIONAL_ATTRIBUTES = [
    'GLOBALS'
  ];

  const OPTIONAL_KEYS = [
    'GLOBALS',
    'content',
    'attributes',
    'ariaAttributes'
  ]; // optional for definition - mainly for communication to developers

  const CONFIG_KEY_TO_ATTRIBUTE = [
    'GLOBALS'
  ];
```

Might be worth making a trait...should make the OPTIONAL_KEYS bit easier.

**Comment by joshbruce** [comment]
Using constants becoming too restrictive and causing bad design patterns - switch to no argument functions.

**Comment by joshbruce** [comment]
Abandoned checking for valid types.

Release ready - time to start using it in a more real way.
